[workspace]
resolver = "2"
members = [
    "truc",
    "truc_runtime",
    "examples/target_types",
    "examples/fibonacci",
    "examples/machin/data",
    "examples/machin/machin",
    "internal/truc_analyzer",
    "asm_tests/truc_asm_1",
]
exclude = [
    "examples/readme"
]
