[package]
name = "truc"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"
description = "Stuff"
documentation = "https://docs.rs/truc"
repository = "https://github.com/arnodb/truc"
readme = "../README.md"

[dependencies]
codegen = "0.1"
derive_more = "0.99"
derive-new = "0.5"
itertools = "0.10"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
truc_runtime = { path = "../truc_runtime" }
