[package]
name = "truc"
version = "0.1.0"
edition = "2021"

[dependencies]
codegen = "0.1"
derive_more = "0.99"
derive-new = "0.5"
itertools = "0.10"
proc-macro2 = "1"
quote = "1"
syn = "1"
truc_runtime = { path = "../truc_runtime" }