[package]
name = "machin_truc"
version = "0.1.0"
edition = "2021"

[dependencies]
machin_data = { path = "../machin_data" }
static_assertions = "1"
truc_runtime = { path = "../truc_runtime" }

[build-dependencies]
machin_data = { path = "../machin_data" }
truc = { path = "../truc" }
