[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies]
static_assertions = "1"
truc_runtime = { path = "../../truc_runtime" }

[build-dependencies]
serde_json = "1"
truc = { path = "../../truc" }
